criacao_epicos_azure_devops:
  description: "criação de epicos a partir de transcrição de reunião"
  status_update: "analisando a transcrição"
  model_name: "claude-sonnet-4-5"
  agent_type: "processador"
  instrucoes_extras: "criacao_epicos_azure_devops"
  provider: "anthropic"

refinamento_epicos_azure_devops:
  description: "criação de epicos a partir de transcrição de reunião"
  status_update: "analisando o histórico"
  model_name: "claude-sonnet-4-5"
  agent_type: "processador"
  instrucoes_extras: "refinamento_epicos_azure_devops"
  provider: "anthropic"

cracao_alocacao_azure_devops:
  description: "criação de epicos a partir de transcrição de reunião"
  status_update: "analisando o histórico"
  model_name: "claude-sonnet-4-5"
  agent_type: "processador"
  instrucoes_extras: "cracao_alocacao_azure_devops"
  provider: "anthropic"
