class JobFields:
    STATUS = 'status'
    DATA = 'data'
    PROJETO = 'projeto'
    REPO_NAME = 'repo_name'
    REPOSITORY_TYPE = 'repository_type'
    BRANCH_NAME = 'branch_name'
    ANALYSIS_REPORT = 'analysis_report'
    REPORT_BLOB_URL = 'report_blob_url'
    GERAR_RELATORIO_APENAS = 'gerar_relatorio_apenas'
    INSTRUCOES_EXTRAS_APROVACAO = 'instrucoes_extras_aprovacao'
    PAUSED_AT_STEP = 'paused_at_step'
    STEP_BATCHES = 'step_batches'
    CURRENT_BATCH_INDEX = 'current_batch_index'
    BATCH_RESULTS = 'batch_results'
    EXECUTAR_STEPS_INCREMENTALMENTE = 'executar_steps_incrementalmente'
    MAX_STEPS_PER_BATCH = 'max_steps_per_batch'
    COMMIT_DETAILS = 'commit_details'
    BUILD_RESULT = 'build_result'
    BUILD_ERRORS = 'build_errors'
    EXECUTAR_BUILD_DOTNET = 'executar_build_dotnet'
    REPO_NAME_MODERNIZADO = 'repo_name_modernizado'
    BRANCH_NAME_MODERNIZADO = 'branch_name_modernizado'
    REPO_NAME_ORIGINAL = 'repo_name_original'
    BRANCH_NAME_ORIGINAL = 'branch_name_original'

class JobStatus:
    WORKFLOW_STARTED = 'workflow_started'
    COMPLETED = 'completed'
    FAILED = 'failed'
    REJECTED = 'rejected'

class JobActions:
    APPROVE = 'approve'
    REJECT = 'reject'
