# Centralização de literais mágicos usadas em múltiplos arquivos

STATUS = "status"
DATA = "data"
JOB_ID = "job_id"
REPOSITORY_TYPE = "repository_type"
REPO_NAME = "repo_name"
BRANCH_NAME = "branch_name"
ANALYSIS_NAME = "analysis_name"
ORIGINAL_ANALYSIS_TYPE = "original_analysis_type"
MODEL_NAME = "model_name"
INSTRUCOES_EXTRAS = "instrucoes_extras"
RETORNAR_LISTA_ARQUIVOS = "retornar_lista_arquivos"
USUARIO_EXECUTOR = "usuario_executor"
ARQUIVOS_ESPECIFICOS = "arquivos_especificos"
COMMIT_DETAILS = "commit_details"
ERROR_DETAILS = "error_details"
ANALYSIS_REPORT = "analysis_report"
DIAGNOSTIC_LOGS = "diagnostic_logs"
REPORT_BLOB_URL = "report_blob_url"
BUILD_ERRORS = "build_errors"
PLATFORM_AZURE = "Azure"
TOKEN_MASK = "***"

# Status de Job centralizados
JOB_STATUS_STARTING = "starting"
JOB_STATUS_PENDING_APPROVAL = "pending_approval"
JOB_STATUS_WORKFLOW_STARTED = "workflow_started"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_REJECTED = "rejected"

# Job Actions
JOB_ACTION_APPROVE = "approve"
JOB_ACTION_REJECT = "reject"
