# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Run Python Tests

# Define os gatilhos (eventos) que iniciarão este workflow
on:
  # Roda quando um commit é enviado (push) para o branch 'main'
  push:
    branches: [ main ]
    
  # Roda quando um Pull Request é aberto (ou atualizado) para o branch 'main'
  # Este é o gatilho mais importante para garantir a qualidade do código.
  pull_request:
    branches: [ teste, main ]

# Define os "trabalhos" (jobs) que o workflow executará
jobs:
  # Nome do nosso job. Pode ser qualquer nome.
  build:
    # Define a máquina virtual onde os testes rodarão. 'ubuntu-latest' é a padrão e recomendada.
    runs-on: ubuntu-latest

    # Define a sequência de passos que o job executará
    steps:
      # Passo 1: Baixar o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o ambiente Python na versão desejada
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Você pode alterar para a versão do seu projeto

      # Passo 3: Instalar as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Rodar os testes unitários com pytest
      - name: Run tests with pytest
        run: |
          pytest
